server:
  port: 8181
  error:
    include-stacktrace: on_param
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kavatar
      username: admin
      password: password
      authentication-database: admin
    redis:
      host: "localhost"
      port: 6379
      password: password
      client-name: ${spring.application.name}
      client-type: lettuce #provide reactive connection
      date_format: "dd-MM-yyyy"
      time_format: "HH:mm:ss"
