server:
  port: 8181
  error:
    include-stacktrace: on_param
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kavatar
      username: admin
      password: password
      authentication-database: admin
    redis:
      host: "localhost"
      port: 6379
      password: password
      client-name: ${spring.application.name}
      client-type: lettuce #provide reactive connection
      date_format: "dd-MM-yyyy"
      time_format: "HH:mm:ss"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/oauth-realm
          jwk-set-uri: http://localhost:8080/realms/oauth-realm/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  keycloak:
    client:
      server-url: http://localhost:8080
      realm: oauth-realm
      client-id: kavatar-client
      client-secret: nQgwm0nTUAoz30bLtcrJNR8CJrHgP9vG
