version: '3.8'
name: mongodb-dev
services:
  kavatar-mongodb-dev:
    container_name: kavatar-mongo-dev-container
    image: mongo:6.0.8-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - kravatar-dev-network

  kavatar-mongo-express-dev:
    container_name: kavatar-mongo-express-dev-container
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: kavatar-mongo-dev-container
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - kavatar-mongodb-dev
    restart: unless-stopped
    networks:
      - kravatar-dev-network

networks:
  kravatar-dev-network:
    driver: bridge

volumes:
  data:
