version: '3.8'
name: redis-dev
services:
  kavatar-redis-dev:
    container_name: kavatar-redis-dev-container
    image: redis:7.2.5-alpine3.20
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass ${DEFAULT_PASSWORD_DEV}
    networks:
      - kravatar-dev-network

networks:
  kravatar-dev-network:
    driver: bridge

